module: "fiscal-brasil"

ingress:
  annotations:
    order: 1
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: next
                port:
                  number: 80

csiSecrets:
  enabled: true
  serviceAccountName: "application-permission"

service:
  type: NodePort

containers:
  - name: frontend
    ports:
      - targetPort: 3000
        port: 80
        protocol: TCP
    resources:
      requests:
        cpu: ${.landingpage-fiscal.build.landingpage.resources.requests.cpu}
        memory: ${.landingpage-fiscal.build.landingpage.resources.requests.memory}
      limits:
        cpu: ${.landingpage-fiscal.build.landingpage.resources.limits.cpu}
        memory: ${.landingpage-fiscal.build.landingpage.resources.limits.memory}
